name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          password: ${{ secrets.DROPLET_PASSWORD }}
          key: ${{ secrets.DROPLET_KEY }}
          script: |
            cd ~
            git clone https://github.com/Callimiro/auth-service.git
            cd auth-service
            git pull origin main
            docker stop auth-service || true
            docker rm auth-service || true
            docker compose up -d